# This is a basic workflow to help you get started with Actions

name: Deploy to ESP8266

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
      
        include:
          - host: guberkray.myftp.org
            port: 8087
            

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Installing platformio
        run: pip3 install -U platformio
      # Runs a set of commands using the runners shell
      - name: Build for ESP8266
        run: pio run --target upload --upload-port ${{ matrix.host }} -e d1_mini_pro_GITHUB
        env: 
          PLATFORMIO_UPLOAD_FLAGS: --port=${{ matrix.port }}

